// Code generated
// This file is a generated precompile contract config with stubbed abstract functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package llmprecompile

import (
	"errors"
	"fmt"
	"log"
	"math/big"
	"strings"

	"github.com/ava-labs/subnet-evm/accounts/abi"
	"github.com/ava-labs/subnet-evm/precompile/contract"
	"github.com/ava-labs/subnet-evm/vmerrs"

	_ "embed"

	"github.com/ethereum/go-ethereum/common"
)

const (
	// Gas costs for each function. These are set to 1 by default.
	// You should set a gas cost for each function in your contract.
	// Generally, you should not set gas costs very low as this may cause your network to be vulnerable to DoS attacks.
	// There are some predefined gas costs in contract/utils.go that you can use.
	ContinueEvaluationGasCost uint64 = 1 /* SET A GAS COST HERE */
	EvaluatePromptGasCost     uint64 = 1 /* SET A GAS COST HERE */
	HealthCheckGasCost        uint64 = 1 /* SET A GAS COST HERE */
)

// CUSTOM CODE STARTS HERE
// Reference imports to suppress errors from unused imports. This code and any unnecessary imports can be removed.
var (
	_ = abi.JSON
	_ = errors.New
	_ = big.NewInt
	_ = vmerrs.ErrOutOfGas
	_ = common.Big0
)

// Singleton StatefulPrecompiledContract and signatures.
var (

	// LLMPrecompileRawABI contains the raw ABI of LLMPrecompile contract.
	//go:embed contract.abi
	LLMPrecompileRawABI string

	LLMPrecompileABI = contract.ParseABI(LLMPrecompileRawABI)

	// Prompt Counter for identification of evaluations
	promptCounterKey = common.BytesToHash([]byte("promptCounter"))

	LLMPrecompilePrecompile = createLLMPrecompilePrecompile()
)

// ILLMContractMethodParams is an auto generated low-level Go binding around an user-defined struct.
type ILLMContractMethodParams struct {
	ContractAddress common.Address
	MethodData      []byte
}

type ContinueEvaluationInput struct {
	PromptId              *big.Int
	ContractMethodResults [][]byte
}

type ContinueEvaluationOutput struct {
	EvaluationDone       bool
	ContractMethodParams []ILLMContractMethodParams
}

type EvaluatePromptOutput struct {
	PromptId             *big.Int
	ContractMethodParams []ILLMContractMethodParams
}

// UnpackContinueEvaluationInput attempts to unpack [input] as ContinueEvaluationInput
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackContinueEvaluationInput(input []byte) (ContinueEvaluationInput, error) {
	inputStruct := ContinueEvaluationInput{}
	err := LLMPrecompileABI.UnpackInputIntoInterface(&inputStruct, "continueEvaluation", input, false)

	return inputStruct, err
}

// PackContinueEvaluation packs [inputStruct] of type ContinueEvaluationInput into the appropriate arguments for continueEvaluation.
func PackContinueEvaluation(inputStruct ContinueEvaluationInput) ([]byte, error) {
	return LLMPrecompileABI.Pack("continueEvaluation", inputStruct.PromptId, inputStruct.ContractMethodResults)
}

// PackContinueEvaluationOutput attempts to pack given [outputStruct] of type ContinueEvaluationOutput
// to conform the ABI outputs.
func PackContinueEvaluationOutput(outputStruct ContinueEvaluationOutput) ([]byte, error) {
	return LLMPrecompileABI.PackOutput("continueEvaluation",
		outputStruct.EvaluationDone,
		outputStruct.ContractMethodParams,
	)
}

// UnpackContinueEvaluationOutput attempts to unpack [output] as ContinueEvaluationOutput
// assumes that [output] does not include selector (omits first 4 func signature bytes)
func UnpackContinueEvaluationOutput(output []byte) (ContinueEvaluationOutput, error) {
	outputStruct := ContinueEvaluationOutput{}
	err := LLMPrecompileABI.UnpackIntoInterface(&outputStruct, "continueEvaluation", output)

	return outputStruct, err
}

// continueEvaluation processes a given prompt ID and an array of contract method results,
// returning a structured response indicating the evaluation status and associated method parameters.
//
// The function performs the following:
// 1. Deducts gas for execution and verifies permissions using the allow list.
// 2. Accepts an input containing:
//    - PromptId: The ID of the evaluation prompt.
//    - ContractMethodResults: An array of byte arrays representing method data.
// 3. Constructs an output with:
//    - EvaluationDone: Always set to false.
//    - ContractMethodParams: An array where each entry includes:
//       - ContractAddress: Fixed to 0x0000000000000000000000000000000000000000.
//       - MethodData: Each corresponding entry from ContractMethodResults.
//
// Output:
// The function returns a packed ABI-compliant byte array containing the constructed output.
func continueEvaluation(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
    if remainingGas, err = contract.DeductGas(suppliedGas, ContinueEvaluationGasCost); err != nil {
        return nil, 0, err
    }
    if readOnly {
        return nil, remainingGas, vmerrs.ErrWriteProtection
    }

    // Unpack input into the arguments to the ContinueEvaluationInput
    // inputStruct, err := UnpackContinueEvaluationInput(input)
    if err != nil {
        return nil, remainingGas, err
    }

    // stateDB := accessibleState.GetStateDB()
    // Create the output with EvaluationDone as false and populate ContractMethodParams
    var output ContinueEvaluationOutput
    output.EvaluationDone = true
    output.ContractMethodParams = make([]ILLMContractMethodParams, 0)

    // output.ContractMethodParams = make([]ILLMContractMethodParams, len(inputStruct.ContractMethodResults))

    // for i, result := range inputStruct.ContractMethodResults {
    //     output.ContractMethodParams[i] = ILLMContractMethodParams{
    //         ContractAddress: common.HexToAddress("0x0000000000000000000000000000000000000000"), // Address 0x0
    //         MethodData:      result,                                                        // Copy result bytes
    //     }
    // }

    // Pack the output to conform to the ABI
    packedOutput, err := PackContinueEvaluationOutput(output)
    if err != nil {
        return nil, remainingGas, err
    }

    // Return the packed output and remaining gas
    return packedOutput, remainingGas, nil
}

// UnpackEvaluatePromptInput attempts to unpack [input] into the string type argument
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackEvaluatePromptInput(input []byte) (string, error) {
	res, err := LLMPrecompileABI.UnpackInput("evaluatePrompt", input, false)
	if err != nil {
		return "", err
	}
	unpacked := *abi.ConvertType(res[0], new(string)).(*string)
	return unpacked, nil
}

// PackEvaluatePrompt packs [prompt] of type string into the appropriate arguments for evaluatePrompt.
// the packed bytes include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackEvaluatePrompt(prompt string) ([]byte, error) {
	return LLMPrecompileABI.Pack("evaluatePrompt", prompt)
}

// PackEvaluatePromptOutput attempts to pack given [outputStruct] of type EvaluatePromptOutput
// to conform the ABI outputs.
func PackEvaluatePromptOutput(outputStruct EvaluatePromptOutput) ([]byte, error) {
	return LLMPrecompileABI.PackOutput("evaluatePrompt",
		outputStruct.PromptId,
		outputStruct.ContractMethodParams,
	)
}

// UnpackEvaluatePromptOutput attempts to unpack [output] as EvaluatePromptOutput
// assumes that [output] does not include selector (omits first 4 func signature bytes)
func UnpackEvaluatePromptOutput(output []byte) (EvaluatePromptOutput, error) {
	outputStruct := EvaluatePromptOutput{}
	err := LLMPrecompileABI.UnpackIntoInterface(&outputStruct, "evaluatePrompt", output)

	return outputStruct, err
}

// GetPromptCounter retrieves the current value of the promptCounter from the StateDB.
func GetPromptCounter(stateDB contract.StateDB) *big.Int {
	value := stateDB.GetState(ContractAddress, promptCounterKey)
	if value == (common.Hash{}) {
		// If not found, initialize to 1
		return big.NewInt(0)
	}
	return new(big.Int).SetBytes(value.Bytes())
}

// IncrementPromptCounter increments the value of promptCounter in the StateDB by 1.
func IncrementPromptCounter(stateDB contract.StateDB) *big.Int {
	currentCounter := GetPromptCounter(stateDB)
	nextCounter := new(big.Int).Add(currentCounter, big.NewInt(1))

	// Store the new value in the StateDB
	stateDB.SetState(ContractAddress, promptCounterKey, common.BigToHash(nextCounter))

	return currentCounter // Return the current value before incrementing
}


// evaluatePrompt generates a unique PromptId (starting from 1 and incrementing with each call)
// and processes the input string, returning it as MethodData in the output.
// The output includes:
// - PromptId: A unique identifier for the prompt.
// - ContractMethodParams: An array containing:
//   - ContractAddress: Fixed at 0x0000000000000000000000000000000000000000.
//   - MethodData: The input string converted to bytes.
// This function ensures ABI compliance and consistent outputs for each invocation.
func evaluatePrompt(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
    if remainingGas, err = contract.DeductGas(suppliedGas, EvaluatePromptGasCost); err != nil {
        return nil, 0, err
    }
    if readOnly {
        return nil, remainingGas, vmerrs.ErrWriteProtection
    }

    // Unpack input into the arguments for EvaluatePromptInput
    inputString, err := UnpackEvaluatePromptInput(input)
    if err != nil {
        return nil, remainingGas, err
    }

    stateDB := accessibleState.GetStateDB()

    // Get and increment the counter for the new PromptId
    currentPromptId := IncrementPromptCounter(stateDB) // Retrieve and update the counter

	log.Printf("Input string: %s", inputString)

	parts := strings.Split(inputString, ",")
    if len(parts) != 3 {
        return nil, remainingGas, fmt.Errorf("invalid input format")
    }

	contractAddress := common.HexToAddress(parts[0])
    to := common.HexToAddress(parts[1])
    amount, ok := new(big.Int).SetString(parts[2], 10)
    if !ok {
        return nil, remainingGas, fmt.Errorf("invalid amount")
    }
	log.Printf("Parsed contractAddress: %s, to: %s, amount: %s", contractAddress.Hex(), to.Hex(), amount.String())



     // Define the ERC20 transfer function ABI
	 erc20ABI := `[{
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"}
        ],
        "name": "transfer",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "nonpayable",
        "type": "function"
    }]`

    // Parse the ABI
    parsedABI, err := abi.JSON(strings.NewReader(erc20ABI))
    if err != nil {
        return nil, remainingGas, fmt.Errorf("failed to parse ABI: %v", err)
    }

    // Get the "transfer" method
    transferMethod, exists := parsedABI.Methods["transfer"]
    if !exists {
        return nil, remainingGas, fmt.Errorf("transfer method not found in ABI")
    }

    // Encode the transfer method data
    methodData, err := transferMethod.Inputs.Pack(to, amount)
    if err != nil {
        return nil, remainingGas, fmt.Errorf("failed to pack transfer method inputs: %v", err)
    }
    log.Printf("Encoded method data: %x", append(transferMethod.ID, methodData...))
    // Create the output
    var output EvaluatePromptOutput
    output.PromptId = currentPromptId
    output.ContractMethodParams = []ILLMContractMethodParams{
        {
            ContractAddress: contractAddress,
            MethodData:      append(transferMethod.ID, methodData...), // Prepend method selector
        },
    }


    // Create the desired output
    // var output EvaluatePromptOutput
    // output.PromptId = currentPromptId
    // output.ContractMethodParams = []ILLMContractMethodParams{
    //     {
    //         ContractAddress: common.HexToAddress("0x0000000000000000000000000000000000000000"), // Address 0x00000000
    //         MethodData:      []byte(inputString),                                             // Convert input string to bytes
    //     },
    // }

    // Pack the output to conform to the ABI
    packedOutput, err := PackEvaluatePromptOutput(output)
    if err != nil {
        return nil, remainingGas, err
    }

    // Return the packed output and remaining gas
    return packedOutput, remainingGas, nil
}


// PackHealthCheck packs the include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackHealthCheck() ([]byte, error) {
	return LLMPrecompileABI.Pack("healthCheck")
}

// PackHealthCheckOutput attempts to pack given healthy of type bool
// to conform the ABI outputs.
func PackHealthCheckOutput(healthy bool) ([]byte, error) {
	return LLMPrecompileABI.PackOutput("healthCheck", healthy)
}

// UnpackHealthCheckOutput attempts to unpack given [output] into the bool type output
// assumes that [output] does not include selector (omits first 4 func signature bytes)
func UnpackHealthCheckOutput(output []byte) (bool, error) {
	res, err := LLMPrecompileABI.Unpack("healthCheck", output)
	if err != nil {
		return false, err
	}
	unpacked := *abi.ConvertType(res[0], new(bool)).(*bool)
	return unpacked, nil
}

func healthCheck(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, HealthCheckGasCost); err != nil {
		return nil, 0, err
	}
	// no input provided for this function

	// CUSTOM CODE STARTS HERE

	output := true
	packedOutput, err := PackHealthCheckOutput(output)
	if err != nil {
		return nil, remainingGas, err
	}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// createLLMPrecompilePrecompile returns a StatefulPrecompiledContract with getters and setters for the precompile.

func createLLMPrecompilePrecompile() contract.StatefulPrecompiledContract {
	var functions []*contract.StatefulPrecompileFunction

	abiFunctionMap := map[string]contract.RunStatefulPrecompileFunc{
		"continueEvaluation": continueEvaluation,
		"evaluatePrompt":     evaluatePrompt,
		"healthCheck":        healthCheck,
	}

	for name, function := range abiFunctionMap {
		method, ok := LLMPrecompileABI.Methods[name]
		if !ok {
			panic(fmt.Errorf("given method (%s) does not exist in the ABI", name))
		}
		functions = append(functions, contract.NewStatefulPrecompileFunction(method.ID, function))
	}
	// Construct the contract with no fallback function.
	statefulContract, err := contract.NewStatefulPrecompileContract(nil, functions)
	if err != nil {
		panic(err)
	}
	return statefulContract
}
