// Code generated
// This file is a generated precompile contract test with the skeleton of test functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package llmprecompile

import (
	"math/big"
	"testing"

	"github.com/ava-labs/subnet-evm/core/state"
	"github.com/ava-labs/subnet-evm/precompile/testutils"
	"github.com/ava-labs/subnet-evm/vmerrs"
	"github.com/ethereum/go-ethereum/common"
	"github.com/stretchr/testify/require"
)

var (
	_ = vmerrs.ErrOutOfGas
	_ = big.NewInt
	_ = common.Big0
	_ = require.New
)

// These tests are run against the precompile contract directly with
// the given input and expected output. They're just a guide to
// help you write your own tests. These tests are for general cases like
// allowlist, readOnly behaviour, and gas cost. You should write your own
// tests for specific cases.
var (
	tests = map[string]testutils.PrecompileTest{
		"readOnly continueEvaluation should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// populate test input here
				testInput := ContinueEvaluationInput{}
				input, err := PackContinueEvaluation(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: ContinueEvaluationGasCost,
			ReadOnly:    true,
			ExpectedErr: vmerrs.ErrWriteProtection.Error(),
		},
		"insufficient gas for continueEvaluation should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// populate test input here
				testInput := ContinueEvaluationInput{}
				input, err := PackContinueEvaluation(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: ContinueEvaluationGasCost - 1,
			ReadOnly:    false,
			ExpectedErr: vmerrs.ErrOutOfGas.Error(),
		},
		"readOnly evaluatePlan should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// set test input to a value here
				var testInput string
				testInput = ""
				input, err := PackEvaluatePlan(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: EvaluatePlanGasCost,
			ReadOnly:    true,
			ExpectedErr: vmerrs.ErrWriteProtection.Error(),
		},
		"insufficient gas for evaluatePlan should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// set test input to a value here
				var testInput string
				testInput = ""
				input, err := PackEvaluatePlan(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: EvaluatePlanGasCost - 1,
			ReadOnly:    false,
			ExpectedErr: vmerrs.ErrOutOfGas.Error(),
		},
		"readOnly evaluatePrompt should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// set test input to a value here
				var testInput string
				testInput = ""
				input, err := PackEvaluatePrompt(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: EvaluatePromptGasCost,
			ReadOnly:    true,
			ExpectedErr: vmerrs.ErrWriteProtection.Error(),
		},
		"insufficient gas for evaluatePrompt should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// set test input to a value here
				var testInput string
				testInput = ""
				input, err := PackEvaluatePrompt(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: EvaluatePromptGasCost - 1,
			ReadOnly:    false,
			ExpectedErr: vmerrs.ErrOutOfGas.Error(),
		},
		"readOnly publishPrimitive should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// populate test input here
				testInput := PublishPrimitiveInput{}
				input, err := PackPublishPrimitive(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: PublishPrimitiveGasCost,
			ReadOnly:    true,
			ExpectedErr: vmerrs.ErrWriteProtection.Error(),
		},
		"insufficient gas for publishPrimitive should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// populate test input here
				testInput := PublishPrimitiveInput{}
				input, err := PackPublishPrimitive(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: PublishPrimitiveGasCost - 1,
			ReadOnly:    false,
			ExpectedErr: vmerrs.ErrOutOfGas.Error(),
		},
		"readOnly publishRobotContract should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// populate test input here
				testInput := PublishRobotContractInput{}
				input, err := PackPublishRobotContract(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: PublishRobotContractGasCost,
			ReadOnly:    true,
			ExpectedErr: vmerrs.ErrWriteProtection.Error(),
		},
		"insufficient gas for publishRobotContract should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// populate test input here
				testInput := PublishRobotContractInput{}
				input, err := PackPublishRobotContract(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: PublishRobotContractGasCost - 1,
			ReadOnly:    false,
			ExpectedErr: vmerrs.ErrOutOfGas.Error(),
		},
		"readOnly publishSystemPrimitive should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// populate test input here
				testInput := PublishSystemPrimitiveInput{}
				input, err := PackPublishSystemPrimitive(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: PublishSystemPrimitiveGasCost,
			ReadOnly:    true,
			ExpectedErr: vmerrs.ErrWriteProtection.Error(),
		},
		"insufficient gas for publishSystemPrimitive should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				// CUSTOM CODE STARTS HERE
				// populate test input here
				testInput := PublishSystemPrimitiveInput{}
				input, err := PackPublishSystemPrimitive(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: PublishSystemPrimitiveGasCost - 1,
			ReadOnly:    false,
			ExpectedErr: vmerrs.ErrOutOfGas.Error(),
		},
	}
)

// TestLLMPrecompileRun tests the Run function of the precompile contract.
func TestLLMPrecompileRun(t *testing.T) {
	// Run tests.
	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			test.Run(t, Module, state.NewTestStateDB(t))
		})
	}
}

// TestPackUnpackQuestionAnswerEventData tests the Pack/UnpackQuestionAnswerEventData.
func TestPackUnpackQuestionAnswerEventData(t *testing.T) {
	// CUSTOM CODE STARTS HERE
	// set test inputs with proper values here

	dataInput := QuestionAnswerEventData{
		Question: "",
		Answer:   "",
	}

	_, data, err := PackQuestionAnswerEvent(
		dataInput,
	)
	require.NoError(t, err)

	unpacked, err := UnpackQuestionAnswerEventData(data)
	require.NoError(t, err)
	require.Equal(t, dataInput, unpacked)
}

func BenchmarkLLMPrecompile(b *testing.B) {
	// Benchmark tests.
	for name, test := range tests {
		b.Run(name, func(b *testing.B) {
			test.Bench(b, Module, state.NewTestStateDB(b))
		})
	}
}
