// Code generated
// This file is a generated precompile contract config with stubbed abstract functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package llmprecompile

import (
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"math/big"
	"strings"

	"github.com/ava-labs/subnet-evm/accounts/abi"
	"github.com/ava-labs/subnet-evm/precompile/contract"
	"github.com/ava-labs/subnet-evm/vmerrs"

	_ "embed"

	"github.com/ethereum/go-ethereum/common"
)

const (
	// Gas costs for each function. These are set to 1 by default.
	// You should set a gas cost for each function in your contract.
	// Generally, you should not set gas costs very low as this may cause your network to be vulnerable to DoS attacks.
	// There are some predefined gas costs in contract/utils.go that you can use.
	ContinueEvaluationGasCost uint64 = 1 /* SET A GAS COST HERE */
	EvaluatePromptGasCost     uint64 = 1 /* SET A GAS COST HERE */
	HealthCheckGasCost        uint64 = 1 /* SET A GAS COST HERE */
)

// CUSTOM CODE STARTS HERE
// Reference imports to suppress errors from unused imports. This code and any unnecessary imports can be removed.
var (
	_ = abi.JSON
	_ = errors.New
	_ = big.NewInt
	_ = vmerrs.ErrOutOfGas
	_ = common.Big0
)


type Arg struct {
	Value  string `json:"value"`
	Lookup bool   `json:"lookup"`
}

type Step struct {
	Method    string   `json:"method,omitempty"`
	Contract  string   `json:"contract,omitempty"`
	ABI       string   `json:"abi,omitempty"`
	Args      []Arg    `json:"args,omitempty"`
	PcStep    bool     `json:"pcStep,omitempty"`
	Condition int      `json:"condition,omitempty"`
	SkipTo    int      `json:"skipTo,omitempty"`
}

const erc20Address = "0x52C84043CD9c865236f11d9Fc9F56aa003c1f922";
var	steps = []Step{
		{
			Method:   "balanceOf",
			Contract: "0x52C84043CD9c865236f11d9Fc9F56aa003c1f922",
			ABI: `[{
				"inputs": [
					{
						"internalType": "address",
						"name": "account",
						"type": "address"
					}
				],
				"name": "balanceOf",
				"outputs": [
					{
						"internalType": "uint256",
						"name": "",
						"type": "uint256"
					}
				],
				"stateMutability": "view",
				"type": "function"
			}]`,
			Args: []Arg{
				{Value: "0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC", Lookup: false},
			},
		},
		{
			Method:   "divide",
			Contract: "0xC6d7eF1e8BEd05586A46Bef5e1E392DF64070503",
			ABI: `[{
				"inputs": [
					{
						"internalType": "uint256",
						"name": "a",
						"type": "uint256"
					},
					{
						"internalType": "uint256",
						"name": "b",
						"type": "uint256"
					}
				],
				"name": "divide",
				"outputs": [
					{
						"internalType": "uint256",
						"name": "",
						"type": "uint256"
					}
				],
				"stateMutability": "pure",
				"type": "function"
			}]`,
			Args: []Arg{
				{Value: "0.1", Lookup: true},
				{Value: "2", Lookup: false},
			},
		},
		{
			Method:   "isLessThanOrEqual",
			Contract: "0xC6d7eF1e8BEd05586A46Bef5e1E392DF64070503",
			ABI: `[{
				"inputs": [
					{
						"internalType": "uint256",
						"name": "a",
						"type": "uint256"
					},
					{
						"internalType": "uint256",
						"name": "b",
						"type": "uint256"
					}
				],
				"name": "isLessThanOrEqual",
				"outputs": [
					{
						"internalType": "bool",
						"name": "",
						"type": "bool"
					}
				],
				"stateMutability": "pure",
				"type": "function"
			}]`,
			Args: []Arg{
				{Value: "1.1", Lookup: true},
				{Value: "10", Lookup: false},
			},
		},
		{
			PcStep:    true,
			Method:    "jumpIf",
			Condition: 2,
			SkipTo:    5,
		},
		{
			Method:   "transfer",
			Contract: "0x52C84043CD9c865236f11d9Fc9F56aa003c1f922",
			ABI: `[{
				"inputs": [
					{
						"internalType": "address",
						"name": "to",
						"type": "address"
					},
					{
						"internalType": "uint256",
						"name": "amount",
						"type": "uint256"
					}
				],
				"name": "transfer",
				"outputs": [
					{
						"internalType": "bool",
						"name": "",
						"type": "bool"
					}
				],
				"stateMutability": "nonpayable",
				"type": "function"
			}]`,
			Args: []Arg{
				{Value: "0xad660da80c8D32E1a4Fb8DF6925A428060b58616", Lookup: false},
				{Value: "1.1", Lookup: true},
			},
		},
	}


	// ProcessArguments converts arguments based on the expected types from the ABI.
func ProcessArguments(inputs abi.Arguments, args []Arg) ([]interface{}, error) {
    if len(inputs) != len(args) {
        return nil, fmt.Errorf("mismatch between expected input count (%d) and provided arguments (%d)", len(inputs), len(args))
    }

    packedArgs := make([]interface{}, len(args))
    for i, input := range inputs {
        expectedType := input.Type.String()
        argValue := args[i].Value

        switch expectedType {
        case "address":
            packedArgs[i] = common.HexToAddress(argValue) // Convert to Ethereum address
        case "uint256":
            bigIntValue := new(big.Int)
            if _, success := bigIntValue.SetString(argValue, 10); !success {
                return nil, fmt.Errorf("invalid uint256 value: %s", argValue)
            }
            packedArgs[i] = bigIntValue
        case "bool":
            if argValue == "true" {
                packedArgs[i] = true
            } else if argValue == "false" {
                packedArgs[i] = false
            } else {
                return nil, fmt.Errorf("invalid boolean value: %s", argValue)
            }
        case "string":
            packedArgs[i] = argValue // Use string as-is
        default:
            return nil, fmt.Errorf("unsupported type: %s", expectedType)
        }

        // Log the conversion
        log.Printf("Arg %d: Value=%v, ConvertedValue=%v, ExpectedType=%s", i, argValue, packedArgs[i], expectedType)
    }

    return packedArgs, nil
}


// Singleton StatefulPrecompiledContract and signatures.
var (

	// LLMPrecompileRawABI contains the raw ABI of LLMPrecompile contract.
	//go:embed contract.abi
	LLMPrecompileRawABI string

	LLMPrecompileABI = contract.ParseABI(LLMPrecompileRawABI)

	// Prompt Counter for identification of evaluations
	promptCounterKey = common.BytesToHash([]byte("promptCounter"))
	stepsKey = common.BytesToHash([]byte("steps"))
    pcKey    = common.BytesToHash([]byte("pc"))

	LLMPrecompilePrecompile = createLLMPrecompilePrecompile()
)

// ILLMContractMethodParams is an auto generated low-level Go binding around an user-defined struct.
type ILLMContractMethodParams struct {
	ContractAddress common.Address
	MethodData      []byte
}

type ContinueEvaluationInput struct {
	PromptId              *big.Int
	ContractMethodResults [][]byte
}

type ContinueEvaluationOutput struct {
	EvaluationDone       bool
	ContractMethodParams []ILLMContractMethodParams
}

type EvaluatePromptOutput struct {
	PromptId             *big.Int
	ContractMethodParams []ILLMContractMethodParams
}

// UnpackContinueEvaluationInput attempts to unpack [input] as ContinueEvaluationInput
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackContinueEvaluationInput(input []byte) (ContinueEvaluationInput, error) {
	inputStruct := ContinueEvaluationInput{}
	err := LLMPrecompileABI.UnpackInputIntoInterface(&inputStruct, "continueEvaluation", input, false)

	return inputStruct, err
}

// PackContinueEvaluation packs [inputStruct] of type ContinueEvaluationInput into the appropriate arguments for continueEvaluation.
func PackContinueEvaluation(inputStruct ContinueEvaluationInput) ([]byte, error) {
	return LLMPrecompileABI.Pack("continueEvaluation", inputStruct.PromptId, inputStruct.ContractMethodResults)
}

// PackContinueEvaluationOutput attempts to pack given [outputStruct] of type ContinueEvaluationOutput
// to conform the ABI outputs.
func PackContinueEvaluationOutput(outputStruct ContinueEvaluationOutput) ([]byte, error) {
	return LLMPrecompileABI.PackOutput("continueEvaluation",
		outputStruct.EvaluationDone,
		outputStruct.ContractMethodParams,
	)
}

// UnpackContinueEvaluationOutput attempts to unpack [output] as ContinueEvaluationOutput
// assumes that [output] does not include selector (omits first 4 func signature bytes)
func UnpackContinueEvaluationOutput(output []byte) (ContinueEvaluationOutput, error) {
	outputStruct := ContinueEvaluationOutput{}
	err := LLMPrecompileABI.UnpackIntoInterface(&outputStruct, "continueEvaluation", output)

	return outputStruct, err
}

// continueEvaluation processes a given prompt ID and an array of contract method results,
// returning a structured response indicating the evaluation status and associated method parameters.
//
// The function performs the following:
// 1. Deducts gas for execution and verifies permissions using the allow list.
// 2. Accepts an input containing:
//    - PromptId: The ID of the evaluation prompt.
//    - ContractMethodResults: An array of byte arrays representing method data.
// 3. Constructs an output with:
//    - EvaluationDone: Always set to false.
//    - ContractMethodParams: An array where each entry includes:
//       - ContractAddress
//       - MethodData
//
// Output:
// The function returns a packed ABI-compliant byte array containing the constructed output.
func continueEvaluation(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
    if remainingGas, err = contract.DeductGas(suppliedGas, ContinueEvaluationGasCost); err != nil {
        return nil, 0, err
    }
    if readOnly {
        return nil, remainingGas, vmerrs.ErrWriteProtection
    }

    // Unpack input into the arguments to the ContinueEvaluationInput
    // inputStruct, err := UnpackContinueEvaluationInput(input)
    if err != nil {
        return nil, remainingGas, err
    }

    // stateDB := accessibleState.GetStateDB()
    // Create the output with EvaluationDone as false and populate ContractMethodParams
    var output ContinueEvaluationOutput
    output.EvaluationDone = true
    output.ContractMethodParams = make([]ILLMContractMethodParams, 0)

    // output.ContractMethodParams = make([]ILLMContractMethodParams, len(inputStruct.ContractMethodResults))

    // for i, result := range inputStruct.ContractMethodResults {
    //     output.ContractMethodParams[i] = ILLMContractMethodParams{
    //         ContractAddress: common.HexToAddress("0x0000000000000000000000000000000000000000"), // Address 0x0
    //         MethodData:      result,                                                        // Copy result bytes
    //     }
    // }

    // Pack the output to conform to the ABI
    packedOutput, err := PackContinueEvaluationOutput(output)
    if err != nil {
        return nil, remainingGas, err
    }

    // Return the packed output and remaining gas
    return packedOutput, remainingGas, nil
}

// UnpackEvaluatePromptInput attempts to unpack [input] into the string type argument
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackEvaluatePromptInput(input []byte) (string, error) {
	res, err := LLMPrecompileABI.UnpackInput("evaluatePrompt", input, false)
	if err != nil {
		return "", err
	}
	unpacked := *abi.ConvertType(res[0], new(string)).(*string)
	return unpacked, nil
}

// PackEvaluatePrompt packs [prompt] of type string into the appropriate arguments for evaluatePrompt.
// the packed bytes include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackEvaluatePrompt(prompt string) ([]byte, error) {
	return LLMPrecompileABI.Pack("evaluatePrompt", prompt)
}

// PackEvaluatePromptOutput attempts to pack given [outputStruct] of type EvaluatePromptOutput
// to conform the ABI outputs.
func PackEvaluatePromptOutput(outputStruct EvaluatePromptOutput) ([]byte, error) {
	return LLMPrecompileABI.PackOutput("evaluatePrompt",
		outputStruct.PromptId,
		outputStruct.ContractMethodParams,
	)
}

// UnpackEvaluatePromptOutput attempts to unpack [output] as EvaluatePromptOutput
// assumes that [output] does not include selector (omits first 4 func signature bytes)
func UnpackEvaluatePromptOutput(output []byte) (EvaluatePromptOutput, error) {
	outputStruct := EvaluatePromptOutput{}
	err := LLMPrecompileABI.UnpackIntoInterface(&outputStruct, "evaluatePrompt", output)

	return outputStruct, err
}

// GetPromptCounter retrieves the current value of the promptCounter from the StateDB.
func GetPromptCounter(stateDB contract.StateDB) *big.Int {
	value := stateDB.GetState(ContractAddress, promptCounterKey)
	if value == (common.Hash{}) {
		// If not found, initialize to 1
		return big.NewInt(0)
	}
	return new(big.Int).SetBytes(value.Bytes())
}

// IncrementPromptCounter increments the value of promptCounter in the StateDB by 1.
func IncrementPromptCounter(stateDB contract.StateDB) *big.Int {
	currentCounter := GetPromptCounter(stateDB)
	nextCounter := new(big.Int).Add(currentCounter, big.NewInt(1))

	// Store the new value in the StateDB
	stateDB.SetState(ContractAddress, promptCounterKey, common.BigToHash(nextCounter))

	return nextCounter // Return the current value before incrementing
}

// Utility function to encode steps into bytes
func encodeSteps(steps []Step) ([]byte, error) {
    encoded, err := json.Marshal(steps)
    if err != nil {
        return nil, fmt.Errorf("failed to encode steps to JSON: %w", err)
    }
    return encoded, nil
}


// evaluatePrompt generates a unique PromptId (starting from 1 and incrementing with each call)
// and processes the input string, returning it as MethodData in the output.
// The output includes:
// - PromptId: A unique identifier for the prompt.
// - ContractMethodParams: An array containing:
//   - ContractAddress
//   - MethodData
// This function ensures ABI compliance and consistent outputs for each invocation.
func evaluatePrompt(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
    if remainingGas, err = contract.DeductGas(suppliedGas, EvaluatePromptGasCost); err != nil {
        return nil, 0, err
    }
    if readOnly {
        return nil, remainingGas, vmerrs.ErrWriteProtection
    }

    // Unpack input into the arguments for EvaluatePromptInput
    inputString, err := UnpackEvaluatePromptInput(input)
    if err != nil {
        return nil, remainingGas, err
    }

	log.Printf("Input string: %s", inputString)


    stateDB := accessibleState.GetStateDB()

    // Get and increment the counter for the new PromptId
    currentPromptId := IncrementPromptCounter(stateDB) // Retrieve and update the counter

	log.Printf("currentPromptId: %v", currentPromptId)

	// Always overwrite the steps in the state database with the current steps
    encodedSteps, err := encodeSteps(steps)
    if err != nil {
        return nil, remainingGas, fmt.Errorf("failed to encode steps: %w", err)
    }
    stateDB.SetState(addr, stepsKey, common.BytesToHash(encodedSteps))



	// Initialize the program counter to zero
    currentPC := big.NewInt(0)
	stateDB.SetState(addr, pcKey, common.BigToHash(currentPC))

	log.Printf("currentPC: %v", currentPC)


	// Fetch the first step
    if len(steps) == 0 {
        return nil, remainingGas, errors.New("no steps available")
    }
    currentStep := steps[0]

	log.Printf("currentStep: %+v", currentStep)

	// Parse the ABI to create a contract object
	parsedABI, err := abi.JSON(strings.NewReader(currentStep.ABI))
	if err != nil {
		return nil, remainingGas, fmt.Errorf("failed to parse ABI: %w", err)
	}

	// Retrieve the method from the parsed contract ABI
	method, exists := parsedABI.Methods[currentStep.Method]
	if !exists {
		return nil, remainingGas, fmt.Errorf("method %s not found in ABI", currentStep.Method)
	}

	log.Printf("method: %s", method)

    // Process the arguments for the method
    packedArgs, err := ProcessArguments(method.Inputs, currentStep.Args)
    if err != nil {
		log.Printf("Error: Failed to process arguments: %v", err)
        return nil, remainingGas, fmt.Errorf("failed to process arguments: %w", err)
    }
    log.Printf("Packed arguments: %+v", packedArgs)

    // Pack the method data
    methodData, err := method.Inputs.Pack(packedArgs...)
    if err != nil {
		log.Printf("Error: Failed to pack method data: %v", err)
        return nil, remainingGas, fmt.Errorf("failed to pack method data: %w", err)
    }
    log.Printf("Method data (hex): %x", methodData)

    // Create contract method params
    contractMethodParams := []ILLMContractMethodParams{
        {
            ContractAddress: common.HexToAddress(currentStep.Contract),
            MethodData:      append(method.ID, methodData...), // Prepend method selector
        },
    }
    log.Printf("Contract Method Params: %+v", contractMethodParams)
	// Prepare the output
	output := EvaluatePromptOutput{
		PromptId:             currentPromptId, // PromptId is irrelevant in this context
		ContractMethodParams: contractMethodParams,
	}

    // Pack the output to conform to the ABI
    packedOutput, err := PackEvaluatePromptOutput(output)
    if err != nil {
        return nil, remainingGas, err
    }

    // Return the packed output and remaining gas
    return packedOutput, remainingGas, nil
}


// PackHealthCheck packs the include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackHealthCheck() ([]byte, error) {
	return LLMPrecompileABI.Pack("healthCheck")
}

// PackHealthCheckOutput attempts to pack given healthy of type bool
// to conform the ABI outputs.
func PackHealthCheckOutput(healthy bool) ([]byte, error) {
	return LLMPrecompileABI.PackOutput("healthCheck", healthy)
}

// UnpackHealthCheckOutput attempts to unpack given [output] into the bool type output
// assumes that [output] does not include selector (omits first 4 func signature bytes)
func UnpackHealthCheckOutput(output []byte) (bool, error) {
	res, err := LLMPrecompileABI.Unpack("healthCheck", output)
	if err != nil {
		return false, err
	}
	unpacked := *abi.ConvertType(res[0], new(bool)).(*bool)
	return unpacked, nil
}

func healthCheck(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, HealthCheckGasCost); err != nil {
		return nil, 0, err
	}
	// no input provided for this function

	// CUSTOM CODE STARTS HERE

	output := true
	packedOutput, err := PackHealthCheckOutput(output)
	if err != nil {
		return nil, remainingGas, err
	}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// createLLMPrecompilePrecompile returns a StatefulPrecompiledContract with getters and setters for the precompile.

func createLLMPrecompilePrecompile() contract.StatefulPrecompiledContract {
	var functions []*contract.StatefulPrecompileFunction

	abiFunctionMap := map[string]contract.RunStatefulPrecompileFunc{
		"continueEvaluation": continueEvaluation,
		"evaluatePrompt":     evaluatePrompt,
		"healthCheck":        healthCheck,
	}

	for name, function := range abiFunctionMap {
		method, ok := LLMPrecompileABI.Methods[name]
		if !ok {
			panic(fmt.Errorf("given method (%s) does not exist in the ABI", name))
		}
		functions = append(functions, contract.NewStatefulPrecompileFunction(method.ID, function))
	}
	// Construct the contract with no fallback function.
	statefulContract, err := contract.NewStatefulPrecompileContract(nil, functions)
	if err != nil {
		panic(err)
	}
	return statefulContract
}
