// Code generated
// This file is a generated precompile contract config with stubbed abstract functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package llmprecompile

import (
    "bytes"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"math/big"
	"strings"

	"github.com/ava-labs/subnet-evm/accounts/abi"
	"github.com/ava-labs/subnet-evm/precompile/contract"
	"github.com/ava-labs/subnet-evm/vmerrs"

	_ "embed"

	"github.com/ethereum/go-ethereum/common"
)

const (
	// Gas costs for each function. These are set to 1 by default.
	// You should set a gas cost for each function in your contract.
	// Generally, you should not set gas costs very low as this may cause your network to be vulnerable to DoS attacks.
	// There are some predefined gas costs in contract/utils.go that you can use.
	ContinueEvaluationGasCost uint64 = 1 /* SET A GAS COST HERE */
	EvaluatePromptGasCost     uint64 = 1 /* SET A GAS COST HERE */
	HealthCheckGasCost        uint64 = 1 /* SET A GAS COST HERE */
)

// CUSTOM CODE STARTS HERE
// Reference imports to suppress errors from unused imports. This code and any unnecessary imports can be removed.
var (
	_ = abi.JSON
	_ = errors.New
	_ = big.NewInt
	_ = vmerrs.ErrOutOfGas
	_ = common.Big0
)


type Arg struct {
	Value  string `json:"value"`
	Lookup int    `json:"lookup"` // Step number to retrieve value from (0 or negative means use Value)
    Key    string `json:"key"` 
}

type Step struct {
	Method    string   `json:"method,omitempty"`
	Contract  string   `json:"contract,omitempty"`
	ABI       string   `json:"abi,omitempty"`
	Args      []Arg    `json:"args,omitempty"`
	PcStep    bool     `json:"pcStep,omitempty"`
	Condition int      `json:"condition,omitempty"`
	SkipTo    int      `json:"skipTo,omitempty"`
}

var	steps = []Step{
	{
		Method:   "increase",
		Contract: "0x17aB05351fC94a1a67Bf3f56DdbB941aE6c63E25",
		ABI: `[{
			"inputs": [
				{
					"internalType": "uint256",
					"name": "number",
					"type": "uint256"
				}
			],
			"name": "increase",
			"outputs": [
				{
					"internalType": "uint256",
					"name": "",
					"type": "uint256"
				}
			],
			"stateMutability": "nonpayable",
			"type": "function"
		}]`,
		Args: []Arg{
			{
				Value: "10",
			},
		},
	},
	{
		Method:   "increase",
		Contract: "0x5aa01B3b5877255cE50cc55e8986a7a5fe29C70e",
		ABI: `[{
			"inputs": [
				{
					"internalType": "uint256",
					"name": "number",
					"type": "uint256"
				}
			],
			"name": "increase",
			"outputs": [
				{
					"internalType": "uint256",
					"name": "",
					"type": "uint256"
				}
			],
			"stateMutability": "nonpayable",
			"type": "function"
		}]`,
		Args: []Arg{
			{
				Value: "20",
			},
		},
	},
}


	// ProcessArguments converts arguments based on the expected types from the ABI.
func ProcessArguments(inputs abi.Arguments, args []Arg) ([]interface{}, error) {
    if len(inputs) != len(args) {
        return nil, fmt.Errorf("mismatch between expected input count (%d) and provided arguments (%d)", len(inputs), len(args))
    }

    packedArgs := make([]interface{}, len(args))
    for i, input := range inputs {
        expectedType := input.Type.String()
        argValue := args[i].Value

        switch expectedType {
        case "address":
            packedArgs[i] = common.HexToAddress(argValue) // Convert to Ethereum address
        case "uint256":
            bigIntValue := new(big.Int)
            if _, success := bigIntValue.SetString(argValue, 10); !success {
                return nil, fmt.Errorf("invalid uint256 value: %s", argValue)
            }
            packedArgs[i] = bigIntValue
        case "bool":
            if argValue == "true" {
                packedArgs[i] = true
            } else if argValue == "false" {
                packedArgs[i] = false
            } else {
                return nil, fmt.Errorf("invalid boolean value: %s", argValue)
            }
        case "string":
            packedArgs[i] = argValue // Use string as-is
        default:
            return nil, fmt.Errorf("unsupported type: %s", expectedType)
        }

        // Log the conversion
        log.Printf("Arg %d: Value=%v, ConvertedValue=%v, ExpectedType=%s", i, argValue, packedArgs[i], expectedType)
    }

    return packedArgs, nil
}


// Singleton StatefulPrecompiledContract and signatures.
var (

	// LLMPrecompileRawABI contains the raw ABI of LLMPrecompile contract.
	//go:embed contract.abi
	LLMPrecompileRawABI string

	LLMPrecompileABI = contract.ParseABI(LLMPrecompileRawABI)

	// Prompt Counter for identification of evaluations
	promptCounterKey = common.BytesToHash([]byte("promptCounter"))
	stepsKey = common.BytesToHash([]byte("steps"))
    pcKey    = common.BytesToHash([]byte("pc"))

	LLMPrecompilePrecompile = createLLMPrecompilePrecompile()
)

// ILLMContractMethodParams is an auto generated low-level Go binding around an user-defined struct.
type ILLMContractMethodParams struct {
	ContractAddress common.Address
	MethodData      []byte
}

type ContinueEvaluationInput struct {
	PromptId              *big.Int
	ContractMethodResults [][]byte
}

type ContinueEvaluationOutput struct {
	EvaluationDone       bool
	ContractMethodParams []ILLMContractMethodParams
}

type EvaluatePromptOutput struct {
	PromptId             *big.Int
	ContractMethodParams []ILLMContractMethodParams
}

// UnpackContinueEvaluationInput attempts to unpack [input] as ContinueEvaluationInput
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackContinueEvaluationInput(input []byte) (ContinueEvaluationInput, error) {
	inputStruct := ContinueEvaluationInput{}
	err := LLMPrecompileABI.UnpackInputIntoInterface(&inputStruct, "continueEvaluation", input, false)

	return inputStruct, err
}

// PackContinueEvaluation packs [inputStruct] of type ContinueEvaluationInput into the appropriate arguments for continueEvaluation.
func PackContinueEvaluation(inputStruct ContinueEvaluationInput) ([]byte, error) {
	return LLMPrecompileABI.Pack("continueEvaluation", inputStruct.PromptId, inputStruct.ContractMethodResults)
}

// PackContinueEvaluationOutput attempts to pack given [outputStruct] of type ContinueEvaluationOutput
// to conform the ABI outputs.
func PackContinueEvaluationOutput(outputStruct ContinueEvaluationOutput) ([]byte, error) {
	return LLMPrecompileABI.PackOutput("continueEvaluation",
		outputStruct.EvaluationDone,
		outputStruct.ContractMethodParams,
	)
}

// UnpackContinueEvaluationOutput attempts to unpack [output] as ContinueEvaluationOutput
// assumes that [output] does not include selector (omits first 4 func signature bytes)
func UnpackContinueEvaluationOutput(output []byte) (ContinueEvaluationOutput, error) {
	outputStruct := ContinueEvaluationOutput{}
	err := LLMPrecompileABI.UnpackIntoInterface(&outputStruct, "continueEvaluation", output)

	return outputStruct, err
}

// Utility function to retrieve and decode steps from state storage
func getStepsFromState(stateDB contract.StateDB, addr common.Address) ([]Step, error) {
    // Retrieve encoded steps from state
    encodedSteps := stateDB.GetState(addr, stepsKey).Bytes()
    if len(encodedSteps) == 0 {
        log.Printf("Error: No steps found in state for address: %s", addr.Hex())
        return nil, errors.New("no steps found in state")
    }

    // Log the raw encoded steps retrieved from the state
    log.Printf("Encoded steps retrieved from state: %s", string(encodedSteps))

    // Unmarshal the encoded steps into the steps struct
    var steps []Step
    if err := json.Unmarshal(encodedSteps, &steps); err != nil {
        log.Printf("Error: Failed to decode steps for address: %s. Raw data: %s. Error: %v", addr.Hex(), string(encodedSteps), err)
        return nil, fmt.Errorf("failed to decode steps: %w", err)
    }

    // Log the successfully decoded steps
    log.Printf("Successfully decoded steps: %+v", steps)
    return steps, nil
}


// Utility function to retrieve the program counter
func getPCFromState(stateDB contract.StateDB, addr common.Address) (*big.Int, error) {
    currentPCBytes := stateDB.GetState(addr, pcKey)
    if currentPCBytes == (common.Hash{}) {
        return nil, errors.New("program counter not initialized")
    }

    // Converting value from 1 to 0
    // savePCToState stores 1 when pc value is 0
    if currentPCBytes == (common.Hash{1}) {
        return big.NewInt(0), nil
    }

    currentPC := new(big.Int).SetBytes(currentPCBytes.Bytes())
    return currentPC, nil
}

// Utility function to save the program counter to state
func savePCToState(stateDB contract.StateDB, addr common.Address, pc *big.Int) {
    // Convert the big.Int value to a padded byte array
    valueToSave := common.BytesToHash(pc.Bytes())
    // using 1 if counter value is 0, getPCFromState throws "program counter not initialized"
    // error when value is 0
    if pc.Sign() == 0 { // Check if pc == 0
        valueToSave = common.Hash{1} // Use a unique marker for 0
    }
    stateDB.SetState(addr, pcKey, valueToSave)
}

// Utility function to decode results
// Utility function to decode results
func decodeResults(method abi.Method, result []byte) (map[string]interface{}, error) {
    decodedResults := make(map[string]interface{})
    log.Printf("Decoding results for method: %s", method.Name)

    // Attempt to unpack the results
    if err := method.Outputs.UnpackIntoMap(decodedResults, result); err != nil {
        log.Printf("Error: Failed to decode results: %v", err)
        return nil, fmt.Errorf("failed to decode results: %w", err)
    }

    // Log the decoded outputs
    if len(decodedResults) == 0 {
        log.Printf("No outputs were decoded for method: %s", method.Name)
    } else {
        for key, value := range decodedResults {
            if key == "" {
                log.Printf("Unnamed output decoded: Value=%v", value)
            } else {
                log.Printf("Output decoded: Key=%s, Value=%v", key, value)
            }
        }
    }

    return decodedResults, nil
}



// Utility function to prepare the next step's contract call
func prepareNextStep(step Step) ([]ILLMContractMethodParams, error) {
    log.Printf("Preparing next step: Method=%s, Contract=%s", step.Method, step.Contract)

    // Parse the ABI
    parsedABI, err := abi.JSON(strings.NewReader(step.ABI))
    if err != nil {
        log.Printf("Error: Failed to parse ABI for step Method=%s, Contract=%s. Error: %v", step.Method, step.Contract, err)
        return nil, fmt.Errorf("failed to parse ABI: %w", err)
    }
    log.Printf("Successfully parsed ABI for Method=%s, Contract=%s", step.Method, step.Contract)

    // Retrieve the method
    method, exists := parsedABI.Methods[step.Method]
    if !exists {
        log.Printf("Error: Method=%s not found in ABI for Contract=%s", step.Method, step.Contract)
        return nil, fmt.Errorf("method %s not found in ABI", step.Method)
    }
    log.Printf("Successfully retrieved method %s from ABI for Contract=%s", step.Method, step.Contract)

    // Process arguments
    packedArgs, err := ProcessArguments(method.Inputs, step.Args)
    if err != nil {
        log.Printf("Error: Failed to process arguments for Method=%s, Contract=%s. Error: %v", step.Method, step.Contract, err)
        return nil, fmt.Errorf("failed to process arguments: %w", err)
    }
    log.Printf("Successfully processed arguments for Method=%s. Packed Arguments: %+v", step.Method, packedArgs)

    // Pack method data
    methodData, err := method.Inputs.Pack(packedArgs...)
    if err != nil {
        log.Printf("Error: Failed to pack method data for Method=%s, Contract=%s. Error: %v", step.Method, step.Contract, err)
        return nil, fmt.Errorf("failed to pack method data: %w", err)
    }
    log.Printf("Successfully packed method data for Method=%s. Method Data (hex): %x", step.Method, methodData)

    // Return the prepared contract method parameters
    contractParams := []ILLMContractMethodParams{
        {
            ContractAddress: common.HexToAddress(step.Contract),
            MethodData:      append(method.ID, methodData...),
        },
    }
    log.Printf("Prepared contract method parameters for Method=%s, Contract=%s: %+v", step.Method, step.Contract, contractParams)

    return contractParams, nil
}


// Utility function to update memory in state storage
func updateMemoryInState(stateDB contract.StateDB, addr common.Address, pc *big.Int, decodedResults map[string]interface{}) error {
    memoryKey := fmt.Sprintf("step_result_%d", pc.Int64())
    memory := make(map[string][]byte)

    for key, value := range decodedResults {
        encodedValue, err := json.Marshal(value)
        if err != nil {
            return fmt.Errorf("failed to encode result for key %s: %w", key, err)
        }
        memory[key] = encodedValue
    }

    encodedMemory, err := json.Marshal(memory)
    if err != nil {
        return fmt.Errorf("failed to encode memory map: %w", err)
    }

    stateDB.SetState(addr, common.BytesToHash([]byte(memoryKey)), common.BytesToHash(encodedMemory))
    return nil
}


// continueEvaluation processes a given prompt ID and an array of contract method results,
// returning a structured response indicating the evaluation status and associated method parameters.
//
// The function performs the following:
// 1. Deducts gas for execution and verifies permissions using the allow list.
// 2. Accepts an input containing:
//    - PromptId: The ID of the evaluation prompt.
//    - ContractMethodResults: An array of byte arrays representing method data.
// 3. Constructs an output with:
//    - EvaluationDone: Always set to false.
//    - ContractMethodParams: An array where each entry includes:
//       - ContractAddress
//       - MethodData
//
// Output:
// The function returns a packed ABI-compliant byte array containing the constructed output.
func continueEvaluation(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
    log.Printf("Starting continueEvaluation function. Caller: %s, Contract Address: %s", caller.Hex(), addr.Hex())

    // Deduct gas
    if remainingGas, err = contract.DeductGas(suppliedGas, ContinueEvaluationGasCost); err != nil {
        log.Printf("Error: Insufficient gas supplied. Error: %v", err)
        return nil, 0, err
    }

    if readOnly {
        log.Printf("Error: Write protection violation. Function is not allowed in read-only mode.")
        return nil, remainingGas, vmerrs.ErrWriteProtection
    }

    stateDB := accessibleState.GetStateDB()

    // Retrieve steps from state using getLargeState
    encodedSteps, err := getLargeState(stateDB, addr, stepsKey)
    if err != nil {
        log.Printf("Error: Failed to retrieve steps from state. Error: %v", err)
        return nil, remainingGas, err
    }
    log.Printf("Encoded steps retrieved from state: %s", string(encodedSteps))

    // Decode the steps
    var steps []Step
    // Remove null bytes from the encoded steps
    sanitizedEncodedSteps := bytes.ReplaceAll(encodedSteps, []byte("\x00"), []byte{})
    if err := json.Unmarshal(sanitizedEncodedSteps, &steps); err != nil {
        log.Printf("Error: Failed to decode steps from state. Error: %v", err)
        return nil, remainingGas, fmt.Errorf("failed to decode steps: %w", err)
    }
    log.Printf("Successfully decoded %d steps from state.", len(steps))

    // Retrieve the program counter
    currentPC, err := getPCFromState(stateDB, addr)
    if err != nil {
        log.Printf("Error: Failed to retrieve the program counter. Error: %v", err)
        return nil, remainingGas, err
    }
    log.Printf("Current program counter: %d", currentPC.Int64())

    // unpacking input values
    inputStruct, err := UnpackContinueEvaluationInput(input)

    // if err := json.Unmarshal(inputString, &inputStruct); err != nil {
    //     log.Printf("Error: Failed to decode input. Error: %v", err)
    //     return nil, remainingGas, fmt.Errorf("failed to decode input: %w", err)
    // }

    if err != nil {
        log.Printf("Error: Failed to unpack input. Error: %v", err)
        return nil, remainingGas, fmt.Errorf("failed to unpack input: %w", err)
    }
    log.Printf("Decoded input. Prompt ID: %d, ContractMethodResults count: %d", inputStruct.PromptId, len(inputStruct.ContractMethodResults))

    // Process the current step
    currentStep := steps[currentPC.Int64()]
    log.Printf("Processing step %d: Method=%s, Contract=%s", currentPC.Int64(), currentStep.Method, currentStep.Contract)

    parsedABI, err := abi.JSON(strings.NewReader(currentStep.ABI))
    if err != nil {
        log.Printf("Error: Failed to parse ABI for step %d. Error: %v", currentPC.Int64(), err)
        return nil, remainingGas, fmt.Errorf("failed to parse ABI: %w", err)
    }
    log.Printf("Successfully parsed ABI for step %d.", currentPC.Int64())

    decodedResults, err := decodeResults(parsedABI.Methods[currentStep.Method], inputStruct.ContractMethodResults[0])
    if err != nil {
        log.Printf("Error: Failed to decode results for step %d. Error: %v", currentPC.Int64(), err)
        return nil, remainingGas, fmt.Errorf("failed to decode results: %w", err)
    }
    log.Printf("Decoded results for step %d: %+v", currentPC.Int64(), decodedResults)

    // Update memory in state
    if err := updateMemoryInState(stateDB, addr, currentPC, decodedResults); err != nil {
        log.Printf("Error: Failed to update memory in state for step %d. Error: %v", currentPC.Int64(), err)
        return nil, remainingGas, err
    }
    log.Printf("Successfully updated memory in state for step %d.", currentPC.Int64())

    // Increment the program counter
    nextPC := currentPC.Add(currentPC, big.NewInt(1))
    savePCToState(stateDB, addr, nextPC)
    log.Printf("Updated program counter to %d.", nextPC.Int64())

    // Check if evaluation is done
    if nextPC.Int64() >= int64(len(steps)) {
        log.Printf("Evaluation completed. No more steps to process.")
        output := ContinueEvaluationOutput{EvaluationDone: true}
        packedOutput, err := PackContinueEvaluationOutput(output)
        if err != nil {
            log.Printf("Error: Failed to pack final output. Error: %v", err)
            return nil, remainingGas, err
        }
        log.Printf("Successfully packed final output. Returning.")
        return packedOutput, remainingGas, nil
    }

    // Prepare the next step
    nextStep := steps[nextPC.Int64()]
    log.Printf("Preparing next step %d: Method=%s, Contract=%s", nextPC.Int64(), nextStep.Method, nextStep.Contract)

    contractMethodParams, err := prepareNextStep(nextStep)
    if err != nil {
        log.Printf("Error: Failed to prepare next step %d. Error: %v", nextPC.Int64(), err)
        return nil, remainingGas, err
    }
    log.Printf("Successfully prepared contract method params for next step %d.", nextPC.Int64())

    // Pack the output for the next step
    output := ContinueEvaluationOutput{
        EvaluationDone:       false,
        ContractMethodParams: contractMethodParams,
    }

    packedOutput, err := PackContinueEvaluationOutput(output)
    if err != nil {
        log.Printf("Error: Failed to pack output for next step %d. Error: %v", nextPC.Int64(), err)
        return nil, remainingGas, err
    }

    log.Printf("Successfully packed output for next step %d. Returning.", nextPC.Int64())
    return packedOutput, remainingGas, nil
}





// UnpackEvaluatePromptInput attempts to unpack [input] into the string type argument
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackEvaluatePromptInput(input []byte) (string, error) {
	res, err := LLMPrecompileABI.UnpackInput("evaluatePrompt", input, false)
	if err != nil {
		return "", err
	}
	unpacked := *abi.ConvertType(res[0], new(string)).(*string)
	return unpacked, nil
}

// PackEvaluatePrompt packs [prompt] of type string into the appropriate arguments for evaluatePrompt.
// the packed bytes include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackEvaluatePrompt(prompt string) ([]byte, error) {
	return LLMPrecompileABI.Pack("evaluatePrompt", prompt)
}

// PackEvaluatePromptOutput attempts to pack given [outputStruct] of type EvaluatePromptOutput
// to conform the ABI outputs.
func PackEvaluatePromptOutput(outputStruct EvaluatePromptOutput) ([]byte, error) {
	return LLMPrecompileABI.PackOutput("evaluatePrompt",
		outputStruct.PromptId,
		outputStruct.ContractMethodParams,
	)
}

// UnpackEvaluatePromptOutput attempts to unpack [output] as EvaluatePromptOutput
// assumes that [output] does not include selector (omits first 4 func signature bytes)
func UnpackEvaluatePromptOutput(output []byte) (EvaluatePromptOutput, error) {
	outputStruct := EvaluatePromptOutput{}
	err := LLMPrecompileABI.UnpackIntoInterface(&outputStruct, "evaluatePrompt", output)

	return outputStruct, err
}

// GetPromptCounter retrieves the current value of the promptCounter from the StateDB.
func GetPromptCounter(stateDB contract.StateDB) *big.Int {
	value := stateDB.GetState(ContractAddress, promptCounterKey)
	if value == (common.Hash{}) {
		// If not found, initialize to 1
		return big.NewInt(0)
	}
	return new(big.Int).SetBytes(value.Bytes())
}

// IncrementPromptCounter increments the value of promptCounter in the StateDB by 1.
func IncrementPromptCounter(stateDB contract.StateDB) *big.Int {
	currentCounter := GetPromptCounter(stateDB)
	nextCounter := new(big.Int).Add(currentCounter, big.NewInt(1))

	// Store the new value in the StateDB
	stateDB.SetState(ContractAddress, promptCounterKey, common.BigToHash(nextCounter))

	return nextCounter // Return the current value before incrementing
}

// Utility function to encode steps into bytes
func encodeSteps(steps []Step) ([]byte, error) {
    encoded, err := json.Marshal(steps)
    if err != nil {
        return nil, fmt.Errorf("failed to encode steps to JSON: %w", err)
    }
    return encoded, nil
}

func setLargeState(stateDB contract.StateDB, addr common.Address, key common.Hash, data []byte) {
    chunks := len(data) / common.HashLength
    if len(data)%common.HashLength != 0 {
        chunks++
    }

    for i := 0; i < chunks; i++ {
        start := i * common.HashLength
        end := (i + 1) * common.HashLength
        if end > len(data) {
            end = len(data)
        }
        chunkKey := common.BytesToHash(append(key.Bytes(), byte(i)))
        stateDB.SetState(addr, chunkKey, common.BytesToHash(data[start:end]))
    }
}

func getLargeState(stateDB contract.StateDB, addr common.Address, key common.Hash) ([]byte, error) {
    var data []byte
    for i := 0; ; i++ {
        chunkKey := common.BytesToHash(append(key.Bytes(), byte(i)))
        chunk := stateDB.GetState(addr, chunkKey).Bytes()

        // checks for empty chunk
        isEmptyChunk := true
		for _, b := range chunk {
			if b != 0 {
				isEmptyChunk = false
				break
			}
		}

		// Break the loop if no valid data is found
		if isEmptyChunk {
			break
		}

        data = append(data, chunk...)
    }
    if len(data) == 0 {
        return nil, errors.New("no data found in state")
    }
    return data, nil
}



// evaluatePrompt generates a unique PromptId (starting from 1 and incrementing with each call)
// and processes the input string, returning it as MethodData in the output.
// The output includes:
// - PromptId: A unique identifier for the prompt.
// - ContractMethodParams: An array containing:
//   - ContractAddress
//   - MethodData
func evaluatePrompt(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
    // Deduct gas
    if remainingGas, err = contract.DeductGas(suppliedGas, EvaluatePromptGasCost); err != nil {
        return nil, 0, err
    }
    if readOnly {
        return nil, remainingGas, vmerrs.ErrWriteProtection
    }

    // Unpack the input to retrieve the string argument
    inputString, err := UnpackEvaluatePromptInput(input)
    if err != nil {
        log.Printf("Error: Failed to unpack input. Error: %v", err)
        return nil, remainingGas, err
    }
    log.Printf("Input string: %s", inputString)

    stateDB := accessibleState.GetStateDB()

    // Increment and log the prompt counter
    currentPromptId := IncrementPromptCounter(stateDB)
    log.Printf("Current Prompt ID: %v", currentPromptId)

    // Encode the steps for storage
    encodedSteps, err := encodeSteps(steps)
    if err != nil {
        log.Printf("Error: Failed to encode steps: %v", err)
        return nil, remainingGas, fmt.Errorf("failed to encode steps: %w", err)
    }
    log.Printf("Encoded steps before storing: %s", string(encodedSteps))

    // Store the encoded steps using setLargeState
    setLargeState(stateDB, addr, stepsKey, encodedSteps)
    log.Printf("Steps stored successfully in state.")

    // Initialize the program counter to 0
    currentPC := big.NewInt(0)
    savePCToState(stateDB, addr, currentPC)
    log.Printf("Initialized program counter to: %v", currentPC)

    // Prepare the first step
    nextStep := steps[0]
    log.Printf("Current step: %+v", nextStep)

    contractMethodParams, err := prepareNextStep(nextStep)
    if err != nil {
        log.Printf("Error: Failed to prepare next step. Error: %v", err)
        return nil, remainingGas, err
    }
    log.Printf("Contract Method Params: %+v", contractMethodParams)

    // Construct the output
    output := EvaluatePromptOutput{
        PromptId:             currentPromptId,
        ContractMethodParams: contractMethodParams,
    }

    // Pack the output for the next step
    packedOutput, err := PackEvaluatePromptOutput(output)
    if err != nil {
        log.Printf("Error: Failed to pack output. Error: %v", err)
        return nil, remainingGas, err
    }

    log.Printf("evaluatePrompt completed successfully.")
    return packedOutput, remainingGas, nil
}





// PackHealthCheck packs the include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackHealthCheck() ([]byte, error) {
	return LLMPrecompileABI.Pack("healthCheck")
}

// PackHealthCheckOutput attempts to pack given healthy of type bool
// to conform the ABI outputs.
func PackHealthCheckOutput(healthy bool) ([]byte, error) {
	return LLMPrecompileABI.PackOutput("healthCheck", healthy)
}

// UnpackHealthCheckOutput attempts to unpack given [output] into the bool type output
// assumes that [output] does not include selector (omits first 4 func signature bytes)
func UnpackHealthCheckOutput(output []byte) (bool, error) {
	res, err := LLMPrecompileABI.Unpack("healthCheck", output)
	if err != nil {
		return false, err
	}
	unpacked := *abi.ConvertType(res[0], new(bool)).(*bool)
	return unpacked, nil
}

func healthCheck(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, HealthCheckGasCost); err != nil {
		return nil, 0, err
	}
	// no input provided for this function

	// CUSTOM CODE STARTS HERE

	output := true
	packedOutput, err := PackHealthCheckOutput(output)
	if err != nil {
		return nil, remainingGas, err
	}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// createLLMPrecompilePrecompile returns a StatefulPrecompiledContract with getters and setters for the precompile.

func createLLMPrecompilePrecompile() contract.StatefulPrecompiledContract {
	var functions []*contract.StatefulPrecompileFunction

	abiFunctionMap := map[string]contract.RunStatefulPrecompileFunc{
		"continueEvaluation": continueEvaluation,
		"evaluatePrompt":     evaluatePrompt,
		"healthCheck":        healthCheck,
	}

	for name, function := range abiFunctionMap {
		method, ok := LLMPrecompileABI.Methods[name]
		if !ok {
			panic(fmt.Errorf("given method (%s) does not exist in the ABI", name))
		}
		functions = append(functions, contract.NewStatefulPrecompileFunction(method.ID, function))
	}
	// Construct the contract with no fallback function.
	statefulContract, err := contract.NewStatefulPrecompileContract(nil, functions)
	if err != nil {
		panic(err)
	}
	return statefulContract
}
